USE master;
GO

--Create server audit file for schema audit
CREATE SERVER AUDIT DAMS_Schema_Audit
TO FILE 
(
    FILEPATH = N'C:\DAMS_Audit\Schema\',
    MAXSIZE = 50 MB,
    MAX_ROLLOVER_FILES = 15,
    RESERVE_DISK_SPACE = OFF
)
WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE);
GO

ALTER SERVER AUDIT DAMS_Schema_Audit
WITH (STATE = ON);
GO


CREATE DATABASE AUDIT SPECIFICATION DAMS_Schema_Audit_Spec
FOR SERVER AUDIT DAMS_Schema_Audit
ADD (SCHEMA_OBJECT_CHANGE_GROUP),              
ADD (SCHEMA_OBJECT_OWNERSHIP_CHANGE_GROUP)
WITH (STATE = ON);
GO