USE master;
GO

--Create audit file for database audit
CREATE SERVER AUDIT DAMS_Database_Audit
TO FILE 
(
    FILEPATH = N'C:\DAMS_Audit\Database\', 
    MAXSIZE = 100 MB,
    MAX_ROLLOVER_FILES = 20,
    RESERVE_DISK_SPACE = OFF
)
WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE);
GO

ALTER SERVER AUDIT DAMS_Database_Audit
WITH (STATE = ON);
GO


CREATE DATABASE AUDIT SPECIFICATION DAMS_Database_Audit_Spec
FOR SERVER AUDIT DAMS_Database_Audit
ADD (DATABASE_OBJECT_ACCESS_GROUP),
ADD (DATABASE_OWNERSHIP_CHANGE_GROUP)
WITH (STATE = ON);
GO
