USE master;
GO

--Create audit file for security audit
CREATE SERVER AUDIT DAMS_Security_Audit
TO FILE 
(
    FILEPATH = N'C:\DAMS_Audit\Security\', 
    MAXSIZE = 150 MB,
    MAX_ROLLOVER_FILES = 30,
    RESERVE_DISK_SPACE = OFF
)
WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE);
GO

ALTER SERVER AUDIT DAMS_Security_Audit
WITH (STATE = ON);
GO


CREATE DATABASE AUDIT SPECIFICATION DAMS_Security_Audit_Spec
FOR SERVER AUDIT DAMS_Security_Audit
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_ROLE_MEMBER_CHANGE_GROUP),
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP),          
ADD (DATABASE_PRINCIPAL_IMPERSONATION_GROUP),
ADD (USER_CHANGE_PASSWORD_GROUP)
WITH (STATE = ON);
GO