--StockIn Table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.StockIn') AND name = 'ValidFrom')
BEGIN
    ALTER TABLE dbo.StockIn
    ADD 
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
END
GO

ALTER TABLE dbo.StockIn
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.StockIn_History, DATA_CONSISTENCY_CHECK = ON));
GO


--Campaign Table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Campaign') AND name = 'ValidFrom')
BEGIN
    ALTER TABLE dbo.Campaign
    ADD 
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
END
GO

ALTER TABLE dbo.Campaign
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Campaign_History, DATA_CONSISTENCY_CHECK = ON));
GO


--PromotionProduct Table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PromotionProduct') AND name = 'ValidFrom')
BEGIN
    ALTER TABLE dbo.PromotionProduct
    ADD 
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
END
GO

ALTER TABLE dbo.PromotionProduct
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.PromotionProduct_History, DATA_CONSISTENCY_CHECK = ON));
GO


--Sales Table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Sales') AND name = 'ValidFrom')
BEGIN
    ALTER TABLE dbo.Sales
    ADD 
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
END
GO

ALTER TABLE dbo.Sales
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.Sales_History, DATA_CONSISTENCY_CHECK = ON));
GO


--SalesItem Table
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.SalesItem') AND name = 'ValidFrom')
BEGIN
    ALTER TABLE dbo.SalesItem
    ADD 
        ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
        ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CAST('9999-12-31 23:59:59.9999999' AS DATETIME2),
        PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
END
GO

ALTER TABLE dbo.SalesItem
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.SalesItem_History, DATA_CONSISTENCY_CHECK = ON));
GO