ALTER TABLE Commission
ADD ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
		DEFAULT SYSUTCDATETIME(),
	ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
		DEFAULT '9999-12-31 23:59:59.9999999',
	PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);

ALTER TABLE Commission
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.CommissionHistory));
