USE DAMS;
GO

CREATE ROLE Admins;
CREATE LOGIN Jay WITH PASSWORD = 'Jay123';
CREATE USER Jay FOR LOGIN Jay;

ALTER ROLE Admins ADD MEMBER Jay;


GRANT CONTROL ON SCHEMA::dbo TO Admins;
GRANT CONTROL ON SCHEMA::AdminProc TO Admins;
GRANT CONTROL ON SCHEMA::MarketingProc TO Admins;
GRANT CONTROL ON SCHEMA::UserPortalDevProc TO Admins;
GRANT CONTROL ON SCHEMA::SupplyChainProc TO Admins;
GRANT CONTROL ON SCHEMA::AuditorProc TO Admins;

