USE DAMS;
GO

CREATE ROLE Auditors;
CREATE LOGIN Jenny WITH PASSWORD = 'Jenny123';
CREATE USER Jenny FOR LOGIN Jenny;

ALTER ROLE Auditors ADD MEMBER Jenny;

GRANT EXECUTE ON SCHEMA::AuditorProc TO Auditors;